Project review : create main files
Hamzaoutdoors/Review-my-project-from-trials- pull request #1
Opened 2021-07-07 17:30 UTC by Hamzaoutdoors

- Added linters config 
   - Github Actions
   - Webhint
   - Stylelint
 - Modificate HTML & CSS files and fix errors
 - Added Readme files with a professional way

2021-07-07 19:07 UTC, Hamzaoutdoors commented on index.html
> +      </section> -->
Please do not leave unused code as a comment in your project. Because unused code as comments makes your code appear not clear 😸

2021-07-07 19:07 UTC, Hamzaoutdoors commented on index.html
> +        <div class="last-div">
It would be greater if you change this div tag to a section tag to make a comment 💯

2021-07-07 19:07 UTC, Hamzaoutdoors commented on style.css
> +  display: flex;
You can make it display: inline-block so they can appear side by side

2021-07-07 19:08 UTC, Hamzaoutdoors reviewed
Hi @Hamzaoutdoors 👋🏾 👋🏾
Good job Hamza, I love that you have remembered to make a pro Readme file because it's the first thing a user reads to get an idea of what the repo contains 👍.
There are just a few issues in your project that you still need to work on to go to the next one but you are almost there!

# **Highlights**
1. Great PR summary ✔️
2. Great Git Workflow ✔️
3. you documented your work in a professional way ✔️

# **Required Changes ♻️**

1. From the project specifications there should be a .gitignore file listing the test.md file. This file should contain the text "This file should be ignored by git". Kindly add this too.
2. Kindly try to add some images to your project.  to enhance the look of the website.

# **Optional suggestions**
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

2021-07-07 21:14 UTC, de-scholar requested changes
Hi <STUDENT_MENTION>, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>


## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-07 21:14 UTC, de-scholar commented on index.html
> +        <div class="last-div">
- [ ] I think it would be nice if you highlight why are you requestion this change

2021-07-07 21:14 UTC, de-scholar commented on style.css
> +  display: flex;
- [ ] I think it would be nice if you highlight why are you requestion this change

2021-07-07 23:24 UTC, Hamzaoutdoors commented on .github/workflows/linters.yml
> +name: Linters
It will be good to also add the .hintrc file to the .gitIgnore. This will make your repo appear more clear

2021-07-08 01:20 UTC, mricanho approved these changes
# Status: ✔️ Project Approved ✔️ 

Hello @Hamzaoutdoors 🔥 

You worked hard in all the instructions that the previous Code Reviewers give you👍🏽 

Now you can merge this branch 🚀 

### 💻 👩🏽‍💻  Happy Coding!  👨🏽‍💻 🖥️

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-08 09:41 UTC, merged